#ifndef __LINUX_VIDEODEV2_SAMSUNG_H2
#define __LINUX_VIDEODEV2_SAMSUNG_H2

#include <videodev2_samsung.h>

#define V4L2_CID_CAMERA_GPS_PROCESSINGMETHOD	(V4L2_CID_CAMERA_CLASS_BASE + 35)

#endif /* __LINUX_VIDEODEV2_SAMSUNG_H2 */
